/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fighter_ndkproject_Test1 */

#ifndef _Included_com_fighter_ndkproject_Test1
#define _Included_com_fighter_ndkproject_Test1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fighter_ndkproject_Test1
 * Method:    stringFromJNI
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fighter_ndkproject_Test1_stringFromJNI
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
