/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fighter_ndkproject_JniTool */

#ifndef _Included_com_fighter_ndkproject_JniTool
#define _Included_com_fighter_ndkproject_JniTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fighter_ndkproject_JniTool
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fighter_ndkproject_JniTool_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_fighter_ndkproject_JniTool
 * Method:    testFromJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fighter_ndkproject_JniTool_testFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
